/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  GnosisSafe,
  GnosisSafeInterface,
} from "../../../contracts/Safe2LinkModule.sol/GnosisSafe";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "enum Enum.Operation",
        name: "operation",
        type: "uint8",
      },
    ],
    name: "execTransactionFromModule",
    outputs: [
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class GnosisSafe__factory {
  static readonly abi = _abi;
  static createInterface(): GnosisSafeInterface {
    return new Interface(_abi) as GnosisSafeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): GnosisSafe {
    return new Contract(address, _abi, runner) as unknown as GnosisSafe;
  }
}
