/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as safe2LinkModuleSol from "./Safe2LinkModule.sol";
export type { safe2LinkModuleSol };
import type * as test from "./test";
export type { test };
